/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9eec7b5b-e481-4a7c-adb2-1960a8cf2f7c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ehyjwoSLl",
    "aws_user_pools_web_client_id": "2gvvrol48i114gvu9m3mmbme7k",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rn7hdew7rjc2bpcwzhbeelfqna.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
